//! Web UI channel — Phase 39.
//!
//! A localhost-only web chat interface that connects to the daemon
//! over the existing IPC protocol via WebSocket. The web server is
//! a background task spawned inside `run_daemon` (same pattern as
//! the webhook listener). Each WebSocket connection bridges directly
//! to the daemon's Unix socket at the frame level — sending
//! `FrontendMessage` frames and forwarding `DaemonEnvelope` frames
//! in real time.
//!
//! `WebDaemonChannel` is the `ChannelContext` stub returned by the
//! daemon's `ChannelFactory` when a `FrontendType::Web` connection
//! arrives. Like `TelegramDaemonChannel`, its `stream_event` and
//! `finalize` are no-ops — the `IpcChannelBridge` handles
//! forwarding those over IPC.

use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};

use futures_util::{SinkExt, StreamExt};
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::{TcpListener, UnixStream};

use aivyx_core::{
    CancellationToken, ChannelContext, ChannelError, ChannelPlatform, SessionId, StreamEvent,
    TurnOutcome,
};

use crate::daemon_ipc::{
    DaemonEnvelope, FrameError, FrontendMessage, FrontendType, decode_frame, encode_frame,
};
use crate::daemon_server::DaemonError;
use crate::notify_webui::{DesktopNotificationFrame, WebUiBroadcastFrame, WebUiBroadcaster};

/// Default web UI port. Adjacent to webhook (7842).
pub const DEFAULT_WEB_UI_PORT: u16 = 7843;

/// No-bundle fallback page. Chapter M serves the Dioxus `aivyx-web` bundle
/// when it's built; this is what `/` serves instead while the bundle is
/// absent (a small "build the Studio bundle" notice, not a UI in its own
/// right — the multi-pane legacy inspector this used to be was retired
/// outright once Audit/Sessions/Learning shipped as real Studio/TUI
/// surfaces).
const HTML: &str = include_str!("web_ui_static.html");

// Chapter M.5 — the embedded Dioxus bundle, generated by `build.rs` from
// `crates/aivyx-web/dist/` (or an empty table when it hasn't been built).
include!(concat!(env!("OUT_DIR"), "/web_assets.rs"));

/// Look up an embedded bundle asset by request path (e.g. `/aivyx-web_bg.wasm`).
fn web_asset(path: &str) -> Option<(&'static [u8], &'static str)> {
    WEB_ASSETS
        .iter()
        .find(|(p, _, _)| *p == path)
        .map(|(_, bytes, mime)| (*bytes, *mime))
}

/// The bundle's `index.html`, when the bundle is built.
fn bundle_index() -> Option<(&'static [u8], &'static str)> {
    web_asset("/index.html")
}

// ---------------------------------------------------------------------------
// WebDaemonChannel — identity stub for the daemon's ChannelFactory
// ---------------------------------------------------------------------------

/// Lightweight `ChannelContext` stub that returns `Trusted` trust
/// tier and `Local` platform. Used by the daemon's `ChannelFactory`
/// when a `FrontendType::Web` connection arrives. The stub's
/// `stream_event` and `finalize` are no-ops — the `IpcChannelBridge`
/// handles forwarding those over IPC.
///
/// `ChannelPlatform::Local` is correct because the web UI is bound
/// to `127.0.0.1` only — the existing `Local` doc says "CLI,
/// desktop app, local REST on 127.0.0.1."
pub struct WebDaemonChannel {
    session: SessionId,
    /// Rotated per turn by [`reset_cancellation`] and fired by
    /// [`cancel_inflight`]. See `TelegramDaemonChannel::token` —
    /// same C1+H1 audit fix.
    token: Mutex<CancellationToken>,
}

impl WebDaemonChannel {
    pub fn new() -> Self {
        WebDaemonChannel {
            session: SessionId::new(),
            token: Mutex::new(CancellationToken::new()),
        }
    }
}

impl Default for WebDaemonChannel {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait::async_trait]
impl ChannelContext for WebDaemonChannel {
    fn channel_name(&self) -> &str {
        "aivyx-web"
    }

    fn platform(&self) -> ChannelPlatform {
        ChannelPlatform::Local
    }

    fn trust_tier(&self) -> aivyx_capability::TrustTier {
        aivyx_capability::TrustTier::Trusted
    }

    fn session_id(&self) -> SessionId {
        self.session
    }

    async fn stream_event(&self, _event: StreamEvent<'_>) -> Result<(), ChannelError> {
        Ok(())
    }

    async fn finalize(&self, _outcome: &TurnOutcome) -> Result<(), ChannelError> {
        Ok(())
    }

    fn cancellation_token(&self) -> CancellationToken {
        self.token.lock().expect("token mutex poisoned").clone()
    }

    fn reset_cancellation(&self) {
        let mut slot = self.token.lock().expect("token mutex poisoned");
        *slot = CancellationToken::new();
    }

    fn cancel_inflight(&self) {
        self.token.lock().expect("token mutex poisoned").cancel();
    }
}

// ---------------------------------------------------------------------------
// Web UI HTTP + WebSocket server
// ---------------------------------------------------------------------------

/// Run the web UI server. Binds `<host>:<port>` (default host
/// `127.0.0.1`), serves the embedded HTML at `GET /`, and upgrades
/// `GET /ws` to WebSocket. Each WS connection bridges to the daemon's
/// Unix socket at `socket_path`.
///
/// `host` is `None` for the default localhost-only posture every native
/// install keeps; Chapter Harbor passes `0.0.0.0` for containerized
/// deployment (Docker forwards published ports to the container's
/// `0.0.0.0`, not its loopback). Binding beyond loopback is a deliberate
/// network exposure — the WS Origin allowlist (below) still defends
/// against CSWSH / DNS-rebinding, and operators front it with auth/TLS.
///
/// Uses `tokio-tungstenite` directly on the TCP stream — each
/// incoming connection is peeked to determine if it's a WebSocket
/// upgrade request for `/ws` or an HTTP request for `/`. This
/// avoids pulling hyper into the WebSocket path.
///
/// This future never returns normally — it runs until `shutdown` is
/// cancelled.
#[allow(clippy::too_many_arguments)]
pub async fn run_web_ui_server(
    socket_path: PathBuf,
    host: Option<std::net::IpAddr>,
    port: u16,
    allowed_origins: Vec<String>,
    auth_token: Option<String>,
    comfyui_base_url: Option<String>,
    shutdown: CancellationToken,
    web_ui_broadcaster: Option<Arc<WebUiBroadcaster>>,
) -> Result<(), DaemonError> {
    let host = host.unwrap_or(std::net::IpAddr::V4(std::net::Ipv4Addr::LOCALHOST));
    let addr = std::net::SocketAddr::new(host, port);
    let allowed_origins = Arc::new(allowed_origins);
    let auth_token = Arc::new(auth_token);
    let comfyui_base_url = Arc::new(comfyui_base_url);
    // POLISH_WAVES.md sub-project 6, item B — one random id per daemon
    // process, stable for its whole lifetime. See `DaemonEnvelope::
    // ServerInfo`'s doc comment (aivyx-ipc) for what this detects.
    let boot_id = Arc::new(uuid::Uuid::new_v4().to_string());

    // Chapter Harbor F-4 — binding beyond loopback is a deliberate network
    // exposure. Warn once at startup so an operator who flips web_ui_host can't
    // miss that the Studio (a powerful agent) is now reachable off-host.
    if !host.is_loopback() {
        eprintln!(
            "aivyx-pa web ui: WARNING — binding {host} (non-loopback). The Studio \
             is exposed beyond this host. Put TLS in front, and set \
             `[daemon] web_ui_allowed_origins` for the hostnames you serve. See \
             docs/DOCKER.md. If a client can't connect even though this \
             process is bound and healthy, check the host's own firewall \
             (ufw/firewalld/iptables) — a green Aivyx-side check (bind, \
             token, cookie, /ws upgrade) says nothing about whether the port \
             is actually reachable from outside this host."
        );
        // Chapter Postern — off-host with no token is an unauthenticated
        // control plane. Escalate the warning; don't refuse (a reverse proxy
        // may add auth), but make the exposure impossible to miss.
        if auth_token.is_none() {
            eprintln!(
                "aivyx-pa web ui: WARNING — no `[daemon] web_ui_auth_token` set \
                 while bound off-host: ANYONE who can reach {addr} can drive \
                 the agent, read memory, and change config. Set a token."
            );
        }
    }
    if auth_token.is_some() {
        eprintln!("aivyx-pa web ui: auth token required for the control plane (/ws)");
    }
    let listener = TcpListener::bind(addr)
        .await
        .map_err(|source| DaemonError::Bind {
            path: addr.to_string(),
            source,
        })?;

    eprintln!("aivyx-pa web ui: listening on http://{addr}");

    let socket_path = Arc::new(socket_path);

    loop {
        let (stream, remote) = tokio::select! {
            result = listener.accept() => {
                match result {
                    Ok(conn) => conn,
                    Err(e) => {
                        eprintln!("aivyx-pa web ui: accept error: {e}");
                        continue;
                    }
                }
            }
            _ = shutdown.cancelled() => return Ok(()),
        };

        let conn_socket_path = Arc::clone(&socket_path);
        let conn_boot_id = Arc::clone(&boot_id);
        let conn_broadcaster = web_ui_broadcaster.clone();
        let conn_allowed_origins = Arc::clone(&allowed_origins);
        let conn_auth_token = Arc::clone(&auth_token);
        let conn_comfyui_base_url = Arc::clone(&comfyui_base_url);

        tokio::spawn(async move {
            if let Err(e) = handle_connection(
                stream,
                remote,
                &conn_socket_path,
                &conn_boot_id,
                port,
                &conn_allowed_origins,
                conn_auth_token.as_deref(),
                conn_comfyui_base_url.as_deref(),
                conn_broadcaster,
            )
            .await
            {
                eprintln!("aivyx-pa web ui: connection error: {e}");
            }
        });
    }
}

// ---------------------------------------------------------------------------
// Chapter Postern — web UI auth token
// ---------------------------------------------------------------------------

/// Cookie name the browser carries back on the `/ws` upgrade (it cannot set
/// request headers on `new WebSocket()`, but same-origin cookies ARE sent on
/// the handshake). Planted on the Basic-Auth'd page load.
const AUTH_COOKIE: &str = "aivyx_web_token";

/// Constant-time byte comparison — avoids leaking the token length/prefix via
/// early-exit timing on a shared secret.
///
/// `pub(crate)` so `webhook_listener.rs`'s bearer-secret auth can reuse this
/// exact implementation rather than duplicating the compare logic (Task 1,
/// 2026-09-16 audit).
pub(crate) fn ct_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    let mut diff = 0u8;
    for (x, y) in a.iter().zip(b.iter()) {
        diff |= x ^ y;
    }
    diff == 0
}

/// First value of a header (case-insensitive name) from a peeked request head.
fn header_value<'a>(request_head: &'a str, name: &str) -> Option<&'a str> {
    request_head.split("\r\n").find_map(|line| {
        line.split_once(':')
            .and_then(|(n, v)| n.trim().eq_ignore_ascii_case(name).then(|| v.trim()))
    })
}

/// `Authorization: Bearer <token>` (non-browser clients).
fn bearer_token(request_head: &str) -> Option<&str> {
    header_value(request_head, "authorization")?
        .strip_prefix("Bearer ")
        .map(str::trim)
}

/// The password half of `Authorization: Basic base64(user:pass)` — how a
/// browser sends the token after the native Basic-Auth prompt.
fn basic_password(request_head: &str) -> Option<String> {
    use base64::Engine;
    let b64 = header_value(request_head, "authorization")?.strip_prefix("Basic ")?;
    let decoded = base64::engine::general_purpose::STANDARD
        .decode(b64.trim())
        .ok()?;
    let creds = String::from_utf8(decoded).ok()?;
    // user:pass — the token is the password (user is ignored).
    creds.split_once(':').map(|(_, pass)| pass.to_string())
}

/// The [`AUTH_COOKIE`] value from the `Cookie` header, if present.
fn cookie_token(request_head: &str) -> Option<String> {
    let cookies = header_value(request_head, "cookie")?;
    cookies.split(';').find_map(|kv| {
        let (k, v) = kv.split_once('=')?;
        (k.trim() == AUTH_COOKIE).then(|| v.trim().to_string())
    })
}

/// True when the request presents the valid token by ANY accepted means:
/// a Bearer header, HTTP Basic password, or the auth cookie.
fn request_carries_token(request_head: &str, token: &str) -> bool {
    let tb = token.as_bytes();
    if bearer_token(request_head).is_some_and(|t| ct_eq(t.as_bytes(), tb)) {
        return true;
    }
    if basic_password(request_head).is_some_and(|p| ct_eq(p.as_bytes(), tb)) {
        return true;
    }
    if cookie_token(request_head).is_some_and(|c| ct_eq(c.as_bytes(), tb)) {
        return true;
    }
    false
}

/// VITRINE.md §0 P2 — a stale saved credential (a browser's saved
/// Basic-Auth password, an old `Authorization: Bearer` value) used to
/// fail completely silently: no client-side "wrong token" indication
/// (the native prompt just re-appears) and nothing in the daemon
/// journal either — the operator needed a packet capture to diagnose.
/// Logs one line per rejecting IP per cooldown window rather than
/// once per request, since a browser that keeps re-submitting the same
/// stale saved value can retry many times per second.
const REJECTED_TOKEN_LOG_COOLDOWN: std::time::Duration = std::time::Duration::from_secs(60);

/// The decision logic, split out from `log_rejected_token_once`'s
/// `eprintln!` side effect so it's directly unit-testable: true (and
/// records `now` against `ip`) the first time `ip` is seen, or once
/// `REJECTED_TOKEN_LOG_COOLDOWN` has elapsed since it was last logged;
/// false otherwise.
fn should_log_rejected_token(
    map: &Mutex<std::collections::HashMap<std::net::IpAddr, std::time::Instant>>,
    ip: std::net::IpAddr,
    now: std::time::Instant,
) -> bool {
    let mut guard = map.lock().expect("rejected-token log map poisoned");
    let should_log = match guard.get(&ip) {
        Some(last) => now.duration_since(*last) >= REJECTED_TOKEN_LOG_COOLDOWN,
        None => true,
    };
    if should_log {
        guard.insert(ip, now);
    }
    should_log
}

fn log_rejected_token_once(ip: std::net::IpAddr) {
    static LAST_LOGGED: std::sync::OnceLock<Mutex<std::collections::HashMap<std::net::IpAddr, std::time::Instant>>> =
        std::sync::OnceLock::new();
    let map = LAST_LOGGED.get_or_init(|| Mutex::new(std::collections::HashMap::new()));
    if should_log_rejected_token(map, ip, std::time::Instant::now()) {
        eprintln!("aivyx-pa web ui: rejected token from {ip}");
    }
}

/// The JSON shape sent to the browser for `POLISH_WAVES.md` sub-project 6,
/// item B. Split out from `handle_websocket`'s send call so the shape is
/// unit-testable without a real connection — mirrors `should_log_rejected_
/// token`'s own split from its side-effecting caller.
fn server_info_json(boot_id: &str) -> serde_json::Value {
    serde_json::json!({
        "type": "ServerInfo",
        "boot_id": boot_id,
    })
}

/// Handle a single TCP connection. Peek at the first bytes to
/// determine the HTTP path, then either serve HTML or upgrade to
/// WebSocket.
// remote_addr (added for the VITRINE.md §0 rate-limited rejected-token
// log line) pushed this past clippy's default 7-argument cap; every
// parameter here is either connection-wide state or a genuinely
// distinct per-connection value, not a natural struct boundary.
#[allow(clippy::too_many_arguments)]
async fn handle_connection(
    stream: tokio::net::TcpStream,
    remote_addr: std::net::SocketAddr,
    socket_path: &Path,
    boot_id: &str,
    port: u16,
    allowed_origins: &[String],
    auth_token: Option<&str>,
    comfyui_base_url: Option<&str>,
    web_ui_broadcaster: Option<Arc<WebUiBroadcaster>>,
) -> Result<(), DaemonError> {
    // Peek at the request head to determine the path *and* read the
    // `Origin` header for the WebSocket origin check. 4 KiB comfortably
    // covers a standard handshake's request line + headers.
    let mut peek_buf = [0u8; 4096];
    let n = stream.peek(&mut peek_buf).await?;
    let request_head = String::from_utf8_lossy(&peek_buf[..n]);

    if request_head.starts_with("GET /ws") {
        // Chapter Postern — the /ws upgrade IS the control plane (agent turns,
        // config writes, memory reads all flow over it). When a token is set it
        // is REQUIRED here, before the origin check even matters. A browser
        // cannot set headers on `new WebSocket()`, so it authenticates via the
        // cookie planted during the Basic-Auth'd page load; a non-browser
        // client can send `Authorization: Bearer <token>` directly.
        if let Some(token) = auth_token {
            if !request_carries_token(&request_head, token) {
                log_rejected_token_once(remote_addr.ip());
                return serve_bytes(
                    stream,
                    "401 Unauthorized",
                    "text/plain; charset=utf-8",
                    b"unauthorized: web UI auth token required",
                )
                .await;
            }
        }
        // CSWSH / DNS-rebinding defense: a browser *always* sends `Origin` on a
        // WebSocket handshake, so a cross-site page trying to drive this
        // localhost daemon (which can write config + the filesystem) is
        // detectable. Reject any `Origin` that isn't one of our own loopback
        // origins on the bound port. A missing `Origin` is a non-browser client
        // (the CLI / Python IPC probe / native apps) and is allowed — those can
        // already reach the Unix socket directly, so they're inside the trust
        // boundary regardless.
        if !ws_origin_allowed(&request_head, port, allowed_origins) {
            return serve_bytes(
                stream,
                "403 Forbidden",
                "text/plain; charset=utf-8",
                b"forbidden: cross-origin websocket rejected",
            )
            .await;
        }

        // WebSocket upgrade — let tokio-tungstenite handle the
        // HTTP 101 handshake and the WebSocket framing.
        let ws_stream = tokio_tungstenite::accept_async(stream)
            .await
            .map_err(|e| DaemonError::WebSocket(format!("ws handshake: {e}")))?;

        handle_websocket(ws_stream, socket_path, boot_id, web_ui_broadcaster).await
    } else {
        // Chapter Postern — gate static routes too when a token is set: the
        // browser gets a native Basic-Auth prompt, and a valid load plants the
        // cookie the /ws upgrade needs. The bundle is inert, but this gives the
        // login UX + cookie in one step.
        let mut set_cookie: Option<String> = None;
        if let Some(token) = auth_token {
            if !request_carries_token(&request_head, token) {
                log_rejected_token_once(remote_addr.ip());
                return serve_bytes_ext(
                    stream,
                    "401 Unauthorized",
                    "text/plain; charset=utf-8",
                    "WWW-Authenticate: Basic realm=\"Aivyx PA Studio\"\r\n",
                    b"unauthorized: web UI auth token required",
                )
                .await;
            }
            set_cookie = Some(format!(
                "Set-Cookie: {AUTH_COOKIE}={token}; HttpOnly; SameSite=Strict; Path=/\r\n"
            ));
        }
        // Studio Gallery — proxy ComfyUI's `/view` so the browser never needs
        // to reach ComfyUI directly (it's bound to the daemon's own
        // loopback, unreachable from another LAN device). Gated by the same
        // token check above, like every other non-`/ws` route.
        if request_path(&request_head) == "/studio-asset" {
            return serve_comfy_asset(stream, &request_head, comfyui_base_url).await;
        }
        // Static HTTP: serve the embedded Dioxus bundle, falling back to the
        // no-bundle notice at `/` while the bundle is unbuilt.
        serve_static(stream, request_path(&request_head), set_cookie.as_deref()).await
    }
}

/// The raw query string (no leading `?`) from an HTTP request line, e.g.
/// `GET /studio-asset?filename=a.png HTTP/1.1` → `filename=a.png`. Empty
/// when there's no `?`.
fn request_query(request_head: &str) -> &str {
    request_head
        .split_whitespace()
        .nth(1)
        .unwrap_or("")
        .split_once('?')
        .map(|(_, q)| q)
        .unwrap_or("")
}

/// Minimal query param lookup with `%XX` percent-decoding. No new
/// dependency: both ends of this URL (browser `<img src>` and the
/// `serve_comfy_asset` → ComfyUI request below) are ours, so a small
/// self-contained codec is simpler than promoting `url`/`urlencoding` to a
/// direct dependency for two call sites.
fn query_param(query: &str, key: &str) -> Option<String> {
    query.split('&').find_map(|kv| {
        let (k, v) = kv.split_once('=')?;
        (k == key).then(|| percent_decode(v))
    })
}

/// Reverses [`percent_encode`]: `%XX` → the decoded byte, everything else
/// passed through as-is. Invalid UTF-8 after decoding falls back to the
/// original (still-encoded) string rather than failing.
fn percent_decode(s: &str) -> String {
    // Byte-indexed throughout (never sub-slices the `&str`) so adversarial
    // input can't panic on a non-UTF-8 char boundary.
    let bytes = s.as_bytes();
    let mut out = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'%' && i + 2 < bytes.len() {
            let hi = (bytes[i + 1] as char).to_digit(16);
            let lo = (bytes[i + 2] as char).to_digit(16);
            if let (Some(hi), Some(lo)) = (hi, lo) {
                out.push((hi * 16 + lo) as u8);
                i += 3;
                continue;
            }
        }
        out.push(bytes[i]);
        i += 1;
    }
    String::from_utf8(out).unwrap_or_else(|_| s.to_string())
}

/// Percent-encodes anything outside `A-Za-z0-9-_.~` — enough for a query
/// value we're building ourselves (filenames/subfolders/type).
fn percent_encode(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for b in s.bytes() {
        if b.is_ascii_alphanumeric() || matches!(b, b'-' | b'_' | b'.' | b'~') {
            out.push(b as char);
        } else {
            out.push_str(&format!("%{b:02X}"));
        }
    }
    out
}

/// Studio Gallery — proxy `GET {COMFYUI_URL}/view?filename=&subfolder=&type=`
/// to the browser. Rejects a `filename`/`subfolder` containing `/` or `..`
/// before building the upstream request (defense in depth — ComfyUI's own
/// `/view` already validates its side, but a proxy shouldn't forward
/// anything odd upstream either).
async fn serve_comfy_asset(
    stream: tokio::net::TcpStream,
    request_head: &str,
    comfyui_base_url: Option<&str>,
) -> Result<(), DaemonError> {
    let Some(base_url) = comfyui_base_url else {
        return serve_bytes(
            stream,
            "404 Not Found",
            "text/plain; charset=utf-8",
            b"no comfyui server configured",
        )
        .await;
    };
    let query = request_query(request_head);
    let Some(filename) = query_param(query, "filename") else {
        return serve_bytes(
            stream,
            "400 Bad Request",
            "text/plain; charset=utf-8",
            b"missing filename",
        )
        .await;
    };
    let subfolder = query_param(query, "subfolder").unwrap_or_default();
    let folder_type = query_param(query, "type").unwrap_or_else(|| "output".to_string());
    if [&filename, &subfolder]
        .iter()
        .any(|s| s.contains('/') || s.contains(".."))
    {
        return serve_bytes(
            stream,
            "400 Bad Request",
            "text/plain; charset=utf-8",
            b"invalid path segment",
        )
        .await;
    }

    let url = format!(
        "{}/view?filename={}&subfolder={}&type={}",
        base_url.trim_end_matches('/'),
        percent_encode(&filename),
        percent_encode(&subfolder),
        percent_encode(&folder_type),
    );

    let resp = match reqwest::get(&url).await {
        Ok(r) if r.status().is_success() => r,
        _ => {
            return serve_bytes(
                stream,
                "502 Bad Gateway",
                "text/plain; charset=utf-8",
                b"comfyui did not return the asset",
            )
            .await;
        }
    };
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream")
        .to_string();
    match resp.bytes().await {
        Ok(body) => serve_bytes(stream, "200 OK", &content_type, &body).await,
        Err(_) => {
            serve_bytes(
                stream,
                "502 Bad Gateway",
                "text/plain; charset=utf-8",
                b"failed reading comfyui response",
            )
            .await
        }
    }
}

/// Extract the `Origin` header value (case-insensitive name) from a peeked
/// HTTP request head, if present.
fn parse_origin(request_head: &str) -> Option<&str> {
    request_head.split("\r\n").find_map(|line| {
        line.split_once(':').and_then(|(name, value)| {
            name.trim()
                .eq_ignore_ascii_case("origin")
                .then(|| value.trim())
        })
    })
}

/// CSWSH defense for the `/ws` upgrade. Returns `true` when the connection may
/// be upgraded:
/// - no `Origin` header → a non-browser client (CLI / IPC probe / native), allowed;
/// - an `Origin` that exactly matches one of our loopback origins on `port`;
/// - an `Origin` that matches an operator-configured `extra_origins` entry
///   (Chapter Harbor `[daemon] web_ui_allowed_origins` — empty by default, so
///   the localhost-only posture is unchanged unless the operator opts in to
///   remote exposure).
///
/// Everything else — a cross-site page's real origin, a rebinding attacker's
/// hostname, or a sandboxed `null` origin — is rejected. Comparison is
/// case-insensitive and ignores a trailing slash on either side.
fn ws_origin_allowed(request_head: &str, port: u16, extra_origins: &[String]) -> bool {
    match parse_origin(request_head) {
        None => true,
        Some(origin) => {
            let origin = origin.trim_end_matches('/');
            let loopback = [
                format!("http://127.0.0.1:{port}"),
                format!("http://localhost:{port}"),
                format!("http://[::1]:{port}"),
            ];
            loopback.iter().any(|a| origin.eq_ignore_ascii_case(a))
                || extra_origins
                    .iter()
                    .any(|a| origin.eq_ignore_ascii_case(a.trim_end_matches('/')))
        }
    }
}

/// Extract the request-target path (no query string) from the HTTP request
/// line, e.g. `GET /aivyx-web_bg.wasm?v=1 HTTP/1.1` → `/aivyx-web_bg.wasm`.
fn request_path(request_line: &str) -> String {
    request_line
        .split_whitespace()
        .nth(1)
        .unwrap_or("/")
        .split('?')
        .next()
        .unwrap_or("/")
        .to_string()
}

/// Serve a static asset over plain HTTP (Chapter M.5).
///
/// `/` → the bundle's `index.html` when built, else the small no-bundle
/// fallback page. Any other path is looked up in the embedded bundle and
/// served with its content-type; a miss is a 404.
async fn serve_static(
    stream: tokio::net::TcpStream,
    path: String,
    set_cookie: Option<&str>,
) -> Result<(), DaemonError> {
    let extra = set_cookie.unwrap_or("");
    if path == "/" || path == "/index.html" {
        return match bundle_index() {
            Some((bytes, mime)) => serve_bytes_ext(stream, "200 OK", mime, extra, bytes).await,
            // No bundle built → the small fallback notice is the whole page.
            None => {
                serve_bytes_ext(
                    stream,
                    "200 OK",
                    "text/html; charset=utf-8",
                    extra,
                    HTML.as_bytes(),
                )
                .await
            }
        };
    }
    match web_asset(&path) {
        Some((bytes, mime)) => serve_bytes_ext(stream, "200 OK", mime, extra, bytes).await,
        None => serve_bytes_ext(stream, "404 Not Found", "text/plain", extra, b"not found").await,
    }
}

/// Write one plain-HTTP response (status line + headers + body, `Connection:
/// close`). `application/wasm` etc. flow through `content_type` so the browser
/// streams + compiles the wasm correctly.
async fn serve_bytes(
    stream: tokio::net::TcpStream,
    status: &str,
    content_type: &str,
    body: &[u8],
) -> Result<(), DaemonError> {
    serve_bytes_ext(stream, status, content_type, "", body).await
}

/// Like [`serve_bytes`], but with an `extra_headers` string of raw header
/// lines (each terminated with `\r\n`, or empty) — used for `Set-Cookie` and
/// `WWW-Authenticate` on the Chapter Postern auth paths.
async fn serve_bytes_ext(
    mut stream: tokio::net::TcpStream,
    status: &str,
    content_type: &str,
    extra_headers: &str,
    body: &[u8],
) -> Result<(), DaemonError> {
    let response = format!(
        "HTTP/1.1 {status}\r\n\
         Content-Type: {content_type}\r\n\
         Content-Length: {}\r\n\
         {extra_headers}\
         Connection: close\r\n\
         \r\n",
        body.len()
    );
    stream.write_all(response.as_bytes()).await?;
    stream.write_all(body).await?;
    stream.flush().await?;
    // Graceful close. `handle_connection` only *peeks* the request line, so the
    // client's request bytes are still unread in the receive buffer. Dropping
    // the socket now would make the OS send a TCP RST instead of a FIN, and that
    // RST can race ahead and truncate a large in-flight body (e.g. the ~1.7 MB
    // wasm — small assets finish before it matters, the wasm did not, which left
    // the browser with a half-streamed module and a blank page). Half-close the
    // write side (FIN), then drain the read side to EOF so the close is clean.
    let _ = stream.shutdown().await;
    let mut sink = [0u8; 1024];
    let _ = tokio::time::timeout(std::time::Duration::from_secs(5), async {
        while let Ok(n) = stream.read(&mut sink).await {
            if n == 0 {
                break;
            }
        }
    })
    .await;
    Ok(())
}

// ---------------------------------------------------------------------------
// WebSocket ↔ daemon IPC bridge
// ---------------------------------------------------------------------------

/// Bridge a single WebSocket connection to the daemon's Unix socket.
/// Runs two concurrent loops:
/// 1. WS→IPC: reads JSON from WebSocket, encodes as IPC frames,
///    sends to the daemon.
/// 2. IPC→WS: reads IPC frames from the daemon, sends JSON over WS.
async fn handle_websocket(
    ws_stream: tokio_tungstenite::WebSocketStream<tokio::net::TcpStream>,
    socket_path: &Path,
    boot_id: &str,
    web_ui_broadcaster: Option<Arc<WebUiBroadcaster>>,
) -> Result<(), DaemonError> {
    // Connect to the daemon's Unix socket.
    let unix_stream = UnixStream::connect(socket_path).await?;
    let (mut unix_reader, mut unix_writer) = unix_stream.into_split();

    // Read DaemonReady from the daemon.
    let mut ipc_buf = Vec::with_capacity(4096);
    loop {
        let mut tmp = [0u8; 4096];
        let n = unix_reader.read(&mut tmp).await?;
        if n == 0 {
            return Err(DaemonError::Protocol(
                "daemon disconnected before DaemonReady".into(),
            ));
        }
        ipc_buf.extend_from_slice(&tmp[..n]);
        match decode_frame::<DaemonEnvelope>(&ipc_buf) {
            Ok((DaemonEnvelope::DaemonReady { .. }, consumed)) => {
                ipc_buf.drain(..consumed);
                break;
            }
            Err(FrameError::IncompleteBuf) => continue,
            Ok((other, _)) => {
                return Err(DaemonError::Protocol(format!(
                    "expected DaemonReady, got {other:?}"
                )));
            }
            Err(e) => return Err(e.into()),
        }
    }

    // Send StartSession with FrontendType::Web.
    let start = FrontendMessage::StartSession {
        role: None,
        frontend_type: Some(FrontendType::Web),
    };
    let frame = encode_frame(&start)?;
    unix_writer.write_all(&frame).await?;

    // Read SessionStarted — forward it to the WebSocket as JSON.
    let session_id: String = loop {
        let mut tmp = [0u8; 4096];
        let n = unix_reader.read(&mut tmp).await?;
        if n == 0 {
            return Err(DaemonError::Protocol(
                "daemon disconnected before SessionStarted".into(),
            ));
        }
        ipc_buf.extend_from_slice(&tmp[..n]);
        match decode_frame::<DaemonEnvelope>(&ipc_buf) {
            Ok((DaemonEnvelope::SessionStarted { session_id }, consumed)) => {
                ipc_buf.drain(..consumed);
                break session_id;
            }
            // The daemon delivers a take-once `RecoveryNotice` between
            // `DaemonReady` and `SessionStarted` to the first frontend
            // that connects after an unclean shutdown (a prior instance
            // crashed / was killed rather than stopped cleanly). It is
            // informational — skip past it and keep waiting for
            // `SessionStarted`. Without this arm the first browser to
            // connect after an unclean shutdown fails the handshake with
            // "expected SessionStarted, got RecoveryNotice" (mirrors the
            // same tolerance the REPL/TUI client already has).
            Ok((DaemonEnvelope::RecoveryNotice { .. }, consumed)) => {
                ipc_buf.drain(..consumed);
                continue;
            }
            Err(FrameError::IncompleteBuf) => continue,
            Ok((other, _)) => {
                return Err(DaemonError::Protocol(format!(
                    "expected SessionStarted, got {other:?}"
                )));
            }
            Err(e) => return Err(e.into()),
        }
    };

    // Split the WebSocket stream. The sink is shared with the
    // optional broadcast relay loop (Phase 69 Task 5), so wrap it
    // behind a Mutex like the unix writer.
    let (ws_sink, mut ws_source) = ws_stream.split();
    let ws_sink = Arc::new(tokio::sync::Mutex::new(ws_sink));

    // Send SessionStarted to the browser.
    let session_started_json = serde_json::json!({
        "type": "SessionStarted",
        "session_id": session_id,
    });
    {
        let mut sink = ws_sink.lock().await;
        let _ = sink
            .send(tokio_tungstenite::tungstenite::Message::Text(
                session_started_json.to_string().into(),
            ))
            .await;
    }

    // Send ServerInfo to the browser (POLISH_WAVES.md sub-project 6, item
    // B) — one shot per connection, same pattern as SessionStarted above.
    let server_info_json = server_info_json(boot_id);
    {
        let mut sink = ws_sink.lock().await;
        let _ = sink
            .send(tokio_tungstenite::tungstenite::Message::Text(
                server_info_json.to_string().into(),
            ))
            .await;
    }

    // Three concurrent loops: WS→IPC, IPC→WS, and (when a
    // broadcaster is configured) Broadcast→WS for Phase 69
    // desktop notifications.
    let unix_writer = Arc::new(tokio::sync::Mutex::new(unix_writer));

    // IPC→WS: read daemon frames, forward as JSON over WebSocket.
    let ipc_to_ws = {
        let ws_sink = Arc::clone(&ws_sink);
        async move {
            let mut buf = ipc_buf; // reuse the buffer from handshake
            loop {
                // Try to decode any buffered frames first.
                loop {
                    match decode_frame::<DaemonEnvelope>(&buf) {
                        Ok((envelope, consumed)) => {
                            buf.drain(..consumed);
                            let json = match serde_json::to_string(&envelope) {
                                Ok(j) => j,
                                Err(e) => {
                                    eprintln!("aivyx-pa web ui: serialize error: {e}");
                                    continue;
                                }
                            };
                            let mut sink = ws_sink.lock().await;
                            if sink
                                .send(tokio_tungstenite::tungstenite::Message::Text(json.into()))
                                .await
                                .is_err()
                            {
                                return; // WebSocket closed
                            }
                        }
                        Err(FrameError::IncompleteBuf) => break,
                        Err(e) => {
                            eprintln!("aivyx-pa web ui: ipc decode error: {e}");
                            return;
                        }
                    }
                }

                // Read more bytes from the daemon.
                let mut tmp = [0u8; 4096];
                match unix_reader.read(&mut tmp).await {
                    Ok(0) => return, // daemon disconnected
                    Ok(n) => buf.extend_from_slice(&tmp[..n]),
                    Err(_) => return,
                }
            }
        }
    };

    // WS→IPC: read JSON from WebSocket, encode as IPC frames, send
    // to daemon.
    let ws_to_ipc = {
        let unix_writer = Arc::clone(&unix_writer);
        async move {
            while let Some(msg_result) = ws_source.next().await {
                let msg = match msg_result {
                    Ok(m) => m,
                    Err(_) => return, // WebSocket error
                };

                let text = match msg {
                    tokio_tungstenite::tungstenite::Message::Text(t) => t,
                    tokio_tungstenite::tungstenite::Message::Close(_) => return,
                    _ => continue, // ignore binary, ping, pong
                };

                // Parse as FrontendMessage and re-encode as IPC frame.
                let frontend_msg: FrontendMessage = match serde_json::from_str(&text) {
                    Ok(m) => m,
                    Err(e) => {
                        eprintln!("aivyx-pa web ui: invalid WS message: {e}");
                        continue;
                    }
                };

                let frame = match encode_frame(&frontend_msg) {
                    Ok(f) => f,
                    Err(e) => {
                        eprintln!("aivyx-pa web ui: encode error: {e}");
                        continue;
                    }
                };

                let mut w = unix_writer.lock().await;
                if w.write_all(&frame).await.is_err() {
                    return; // daemon disconnected
                }
            }
        }
    };

    // Broadcast→WS (Phase 69 Task 5): if a WebUiBroadcaster is
    // configured, subscribe a fresh receiver and relay every
    // `WebUiBroadcastFrame` onto its matching `DaemonEnvelope`
    // variant. On `Lagged` we drop the missed frames silently:
    // desktop notifications are inherently discardable (a tab the
    // operator isn't watching missing one is fine); a missed
    // TeamMissionUpdated is tolerable because the poll reconciles
    // (see aivyx-web's running_overlay, which self-heals once a
    // poll's checkpoint state supersedes a stale remembered marker)
    // — either way, keep listening rather than closing the connection.
    let broadcast_to_ws = {
        let ws_sink = Arc::clone(&ws_sink);
        let mut rx_opt = web_ui_broadcaster.as_ref().map(|bc| bc.subscribe());
        async move {
            let Some(rx) = rx_opt.as_mut() else {
                // No broadcaster wired — this future never
                // completes, so the `select!` only fires on the
                // other two arms.
                std::future::pending::<()>().await;
                return;
            };
            loop {
                let envelope = match rx.recv().await {
                    Ok(WebUiBroadcastFrame::DesktopNotification(DesktopNotificationFrame {
                        title,
                        body,
                    })) => DaemonEnvelope::DesktopNotification { title, body },
                    Ok(WebUiBroadcastFrame::TeamMissionUpdated(view)) => {
                        DaemonEnvelope::TeamMissionUpdated { view }
                    }
                    Err(tokio::sync::broadcast::error::RecvError::Lagged(_)) => {
                        // Skipped some frames; keep listening.
                        continue;
                    }
                    Err(tokio::sync::broadcast::error::RecvError::Closed) => return,
                };
                let json = match serde_json::to_string(&envelope) {
                    Ok(j) => j,
                    Err(e) => {
                        eprintln!("aivyx-pa web ui: broadcast serialize error: {e}");
                        continue;
                    }
                };
                let mut sink = ws_sink.lock().await;
                if sink
                    .send(tokio_tungstenite::tungstenite::Message::Text(json.into()))
                    .await
                    .is_err()
                {
                    return; // WebSocket closed
                }
            }
        }
    };

    // Run all three loops concurrently. When any exits, the
    // connection is done.
    tokio::select! {
        _ = ipc_to_ws => {}
        _ = ws_to_ipc => {}
        _ = broadcast_to_ws => {}
    }

    // Send Disconnect to the daemon (best effort).
    if let Ok(frame) = encode_frame(&FrontendMessage::Disconnect) {
        let mut w = unix_writer.lock().await;
        let _ = w.write_all(&frame).await;
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn web_channel_platform_is_local() {
        let ch = WebDaemonChannel::new();
        assert_eq!(ch.platform(), ChannelPlatform::Local);
    }

    #[test]
    fn rejected_token_logging_is_rate_limited_per_ip() {
        // VITRINE.md §0 P2 — a browser silently re-submitting the same
        // stale saved credential could hit this many times per second;
        // the log line must collapse to one per cooldown window, not
        // one per rejected request.
        use std::collections::HashMap;
        use std::net::{IpAddr, Ipv4Addr};
        use std::time::{Duration, Instant};

        let map: Mutex<HashMap<IpAddr, Instant>> = Mutex::new(HashMap::new());
        let ip_a = IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1));
        let ip_b = IpAddr::V4(Ipv4Addr::new(10, 80, 80, 148));
        let t0 = Instant::now();

        // First rejection from a given IP always logs.
        assert!(should_log_rejected_token(&map, ip_a, t0));
        // A repeat well within the cooldown window does not.
        assert!(!should_log_rejected_token(
            &map,
            ip_a,
            t0 + Duration::from_secs(1)
        ));
        assert!(!should_log_rejected_token(
            &map,
            ip_a,
            t0 + REJECTED_TOKEN_LOG_COOLDOWN - Duration::from_secs(1)
        ));
        // Once the cooldown has genuinely elapsed, it logs again.
        assert!(should_log_rejected_token(
            &map,
            ip_a,
            t0 + REJECTED_TOKEN_LOG_COOLDOWN
        ));
        // A different IP is tracked independently — not starved by ip_a's
        // own cooldown.
        assert!(should_log_rejected_token(&map, ip_b, t0));
    }

    #[test]
    fn server_info_json_shape() {
        let v = server_info_json("abc-123");
        assert_eq!(v["type"], "ServerInfo");
        assert_eq!(v["boot_id"], "abc-123");
    }

    #[test]
    fn request_path_extracts_target_without_query() {
        assert_eq!(request_path("GET / HTTP/1.1"), "/");
        assert_eq!(
            request_path("GET /aivyx-web_bg.wasm HTTP/1.1"),
            "/aivyx-web_bg.wasm"
        );
        assert_eq!(request_path("GET /app.js?v=abc123 HTTP/1.1"), "/app.js");
        assert_eq!(request_path("garbage"), "/");
    }

    // ---- Chapter Postern — web UI auth token --------------------------

    #[test]
    fn ct_eq_matches_only_identical_bytes() {
        assert!(ct_eq(b"secret", b"secret"));
        assert!(!ct_eq(b"secret", b"secreT"));
        assert!(!ct_eq(b"secret", b"secre")); // length differs
        assert!(ct_eq(b"", b""));
    }

    #[test]
    fn request_carries_token_via_bearer() {
        let head = "GET /ws HTTP/1.1\r\nAuthorization: Bearer tok-123\r\n\r\n";
        assert!(request_carries_token(head, "tok-123"));
        assert!(!request_carries_token(head, "wrong"));
    }

    #[test]
    fn request_carries_token_via_basic_password() {
        use base64::Engine;
        // Browser sends base64("user:token") — the password half is the token.
        let creds = base64::engine::general_purpose::STANDARD.encode("anyuser:tok-123");
        let head = format!("GET / HTTP/1.1\r\nAuthorization: Basic {creds}\r\n\r\n");
        assert!(request_carries_token(&head, "tok-123"));
        let bad = base64::engine::general_purpose::STANDARD.encode("anyuser:nope");
        let head_bad = format!("GET / HTTP/1.1\r\nAuthorization: Basic {bad}\r\n\r\n");
        assert!(!request_carries_token(&head_bad, "tok-123"));
    }

    #[test]
    fn request_carries_token_via_cookie() {
        // The /ws upgrade path: a browser can't set headers, but sends cookies.
        let head = "GET /ws HTTP/1.1\r\nCookie: other=1; aivyx_web_token=tok-123; x=y\r\n\r\n";
        assert!(request_carries_token(head, "tok-123"));
        let head_wrong = "GET /ws HTTP/1.1\r\nCookie: aivyx_web_token=stale\r\n\r\n";
        assert!(!request_carries_token(head_wrong, "tok-123"));
    }

    #[test]
    fn no_credentials_is_rejected() {
        let head = "GET /ws HTTP/1.1\r\nOrigin: http://127.0.0.1:7843\r\n\r\n";
        assert!(!request_carries_token(head, "tok-123"));
    }

    #[test]
    fn web_asset_lookup_finds_index_and_misses_unknown_paths() {
        // Since Chapter R the `aivyx-web/dist/` bundle is committed and embedded
        // by build.rs, so the table is populated: `/index.html` resolves (the
        // SPA entry the daemon serves at `/`), while an unknown path misses
        // (→ 404). `WEB_ASSETS` is `&[]` only in the degenerate build where
        // dist/ was deleted — not the shipped configuration.
        assert!(
            bundle_index().is_some(),
            "the committed dist/ bundle must embed index.html",
        );
        assert!(web_asset("/index.html").is_some());
        assert!(
            web_asset("/definitely-not-an-asset.js").is_none(),
            "unknown asset paths miss",
        );
    }

    #[test]
    fn parse_origin_is_case_insensitive_and_optional() {
        let head =
            "GET /ws HTTP/1.1\r\nHost: 127.0.0.1:7843\r\nOrigin: http://127.0.0.1:7843\r\n\r\n";
        assert_eq!(parse_origin(head), Some("http://127.0.0.1:7843"));
        // header-name case must not matter
        let lower = "GET /ws HTTP/1.1\r\norigin:   http://localhost:7843  \r\n\r\n";
        assert_eq!(parse_origin(lower), Some("http://localhost:7843"));
        // absent
        let none = "GET /ws HTTP/1.1\r\nHost: 127.0.0.1:7843\r\n\r\n";
        assert_eq!(parse_origin(none), None);
    }

    #[test]
    fn ws_origin_allows_loopback_and_no_origin_rejects_cross_site() {
        let port = 7843;
        let none: &[String] = &[];
        let head = |o: &str| format!("GET /ws HTTP/1.1\r\nHost: x\r\nOrigin: {o}\r\n\r\n");
        // our own loopback origins on the bound port — allowed
        assert!(ws_origin_allowed(
            &head("http://127.0.0.1:7843"),
            port,
            none
        ));
        assert!(ws_origin_allowed(
            &head("http://localhost:7843"),
            port,
            none
        ));
        assert!(ws_origin_allowed(&head("http://[::1]:7843"), port, none));
        assert!(ws_origin_allowed(
            &head("HTTP://LOCALHOST:7843"),
            port,
            none
        )); // case-insensitive
        // non-browser client (no Origin) — allowed (inside the trust boundary)
        assert!(ws_origin_allowed(
            "GET /ws HTTP/1.1\r\nHost: x\r\n\r\n",
            port,
            none
        ));
        // CSWSH: a malicious page's real origin — rejected
        assert!(!ws_origin_allowed(&head("http://evil.example"), port, none));
        // DNS rebinding: attacker hostname resolving to 127.0.0.1 — rejected
        assert!(!ws_origin_allowed(
            &head("http://attacker.test:7843"),
            port,
            none
        ));
        // wrong port (another local app) — rejected
        assert!(!ws_origin_allowed(
            &head("http://127.0.0.1:9999"),
            port,
            none
        ));
        // sandboxed/file origin — rejected
        assert!(!ws_origin_allowed(&head("null"), port, none));
    }

    #[test]
    fn ws_origin_honors_configured_allowlist() {
        // Chapter Harbor — an operator-configured origin is allowed in addition
        // to loopback; everything else still rejected. Empty allowlist keeps the
        // localhost-only posture (covered above).
        let port = 7843;
        let head = |o: &str| format!("GET /ws HTTP/1.1\r\nHost: x\r\nOrigin: {o}\r\n\r\n");
        let allow = vec!["https://studio.mybox.lan".to_string()];
        // configured origin — allowed (trailing-slash + case insensitive)
        assert!(ws_origin_allowed(
            &head("https://studio.mybox.lan"),
            port,
            &allow
        ));
        assert!(ws_origin_allowed(
            &head("https://studio.mybox.lan/"),
            port,
            &allow
        ));
        assert!(ws_origin_allowed(
            &head("HTTPS://Studio.MyBox.LAN"),
            port,
            &allow
        ));
        // loopback still allowed alongside the configured one
        assert!(ws_origin_allowed(
            &head("http://localhost:7843"),
            port,
            &allow
        ));
        // a different host is still rejected
        assert!(!ws_origin_allowed(
            &head("https://evil.example"),
            port,
            &allow
        ));
        // and an http:// variant of the https allowlisted host is NOT a match
        assert!(!ws_origin_allowed(
            &head("http://studio.mybox.lan"),
            port,
            &allow
        ));
    }

    #[test]
    fn web_channel_trust_tier_is_trusted() {
        let ch = WebDaemonChannel::new();
        assert_eq!(ch.trust_tier(), aivyx_capability::TrustTier::Trusted);
    }

    #[test]
    fn web_channel_name() {
        let ch = WebDaemonChannel::new();
        assert_eq!(ch.channel_name(), "aivyx-web");
    }

    // Audit C1+H1 regression — same coverage as the
    // Telegram / Discord / Slack daemon stubs.
    #[test]
    fn cancel_inflight_then_reset_yields_fresh_token() {
        let ch = WebDaemonChannel::new();
        let stale = ch.cancellation_token();
        assert!(!stale.is_cancelled());
        ch.cancel_inflight();
        assert!(stale.is_cancelled(), "cancel_inflight fires the live token");
        ch.reset_cancellation();
        assert!(
            !ch.cancellation_token().is_cancelled(),
            "reset_cancellation installs a fresh token"
        );
        assert!(stale.is_cancelled(), "the pre-reset token stays cancelled");
    }

    #[test]
    fn default_port_is_7843() {
        assert_eq!(DEFAULT_WEB_UI_PORT, 7843);
    }

    #[test]
    fn html_is_non_empty() {
        assert!(!HTML.is_empty(), "embedded HTML must not be empty");
        assert!(
            HTML.contains("<html"),
            "embedded HTML must contain <html tag"
        );
    }

    // The Phase 47/69/70/73/74/78 `HTML.contains(...)` regression tests that
    // used to live here characterized the legacy multi-pane inspector's
    // markup (chat/missions/audit/sessions tabs, memory/learning/
    // notifications/proposals pane wiring, desktop-notification JS). That
    // content no longer exists — `/classic` retirement (this chapter)
    // replaced `web_ui_static.html` with the small no-bundle fallback page
    // below, and each of those panes now has a real Studio/TUI equivalent
    // (or, for chat/missions, already did). Removed rather than adapted:
    // there's no successor markup in this file for a substring test to
    // check against — the real coverage for those panes now lives in
    // `aivyx-web`'s own tests.

    // ---- Chapter Postern — end-to-end server auth over real TCP -------

    /// Grab a free localhost port by binding then dropping a listener.
    async fn free_port() -> u16 {
        tokio::net::TcpListener::bind("127.0.0.1:0")
            .await
            .unwrap()
            .local_addr()
            .unwrap()
            .port()
    }

    async fn http_roundtrip(port: u16, request: &str) -> String {
        use tokio::io::{AsyncReadExt, AsyncWriteExt};
        let mut s = tokio::net::TcpStream::connect(("127.0.0.1", port))
            .await
            .unwrap();
        s.write_all(request.as_bytes()).await.unwrap();
        s.flush().await.unwrap();
        let mut buf = Vec::new();
        let _ =
            tokio::time::timeout(std::time::Duration::from_secs(3), s.read_to_end(&mut buf)).await;
        String::from_utf8_lossy(&buf).into_owned()
    }

    #[tokio::test]
    async fn server_enforces_auth_token_end_to_end() {
        let port = free_port().await;
        let shutdown = CancellationToken::new();
        let server_shutdown = shutdown.clone();
        // socket_path is only touched AFTER auth passes (on a real /ws bridge),
        // so a bogus path is fine for the rejection assertions here.
        let handle = tokio::spawn(async move {
            let _ = run_web_ui_server(
                PathBuf::from("/nonexistent/aivyx-postern-test.sock"),
                Some(std::net::IpAddr::V4(std::net::Ipv4Addr::LOCALHOST)),
                port,
                Vec::new(),
                Some("tok-abc123".to_string()),
                None,
                server_shutdown,
                None,
            )
            .await;
        });
        // Give the listener a moment to bind.
        tokio::time::sleep(std::time::Duration::from_millis(150)).await;

        // (1) Static request with NO credentials → 401 + Basic challenge.
        let resp = http_roundtrip(port, "GET / HTTP/1.1\r\nHost: x\r\n\r\n").await;
        assert!(
            resp.starts_with("HTTP/1.1 401"),
            "no-auth static: {resp:.60}"
        );
        assert!(
            resp.contains("WWW-Authenticate: Basic"),
            "must challenge: {resp:.120}"
        );

        // (2) Static request WITH the Basic password → 200 + Set-Cookie.
        use base64::Engine;
        let creds = base64::engine::general_purpose::STANDARD.encode("u:tok-abc123");
        let ok = http_roundtrip(
            port,
            &format!("GET / HTTP/1.1\r\nHost: x\r\nAuthorization: Basic {creds}\r\n\r\n"),
        )
        .await;
        assert!(ok.starts_with("HTTP/1.1 200"), "authed static: {ok:.60}");
        assert!(
            ok.contains(&format!("Set-Cookie: {AUTH_COOKIE}=tok-abc123")),
            "must plant the cookie for the /ws upgrade",
        );

        // (3) /ws upgrade with NO cookie/creds → 401 (control plane closed).
        let ws = http_roundtrip(
            port,
            "GET /ws HTTP/1.1\r\nHost: x\r\nOrigin: http://127.0.0.1\r\nUpgrade: websocket\r\n\r\n",
        )
        .await;
        assert!(
            ws.starts_with("HTTP/1.1 401"),
            "unauth /ws must be 401: {ws:.60}"
        );

        shutdown.cancel();
        let _ = handle.await;
    }

    #[tokio::test]
    async fn classic_route_is_gone() {
        // /classic used to serve the legacy multi-pane inspector (HTML::as_bytes())
        // with a 200. With that route removed, the path falls through
        // `serve_static`'s asset lookup like any other unknown path, which
        // returns a real "404 Not Found" status line — not a redirect, not the
        // legacy HTML, and not the `/`-fallback page either.
        let port = free_port().await;
        let shutdown = CancellationToken::new();
        let server_shutdown = shutdown.clone();
        let handle = tokio::spawn(async move {
            let _ = run_web_ui_server(
                PathBuf::from("/nonexistent/aivyx-classic-retirement-test.sock"),
                Some(std::net::IpAddr::V4(std::net::Ipv4Addr::LOCALHOST)),
                port,
                Vec::new(),
                None, // no auth token — isolate this test to routing, not Postern
                None,
                server_shutdown,
                None,
            )
            .await;
        });
        tokio::time::sleep(std::time::Duration::from_millis(150)).await;

        let resp = http_roundtrip(port, "GET /classic HTTP/1.1\r\nHost: x\r\n\r\n").await;
        assert!(
            resp.starts_with("HTTP/1.1 404"),
            "/classic must 404 now that the route is gone: {resp:.120}"
        );

        shutdown.cancel();
        let _ = handle.await;
    }
}
